## Default values for Wordpress deployment

replicaCount: 1

image:
  registry: "docker.io"
  repository: "wordpress"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

customLabels: {}
customAnnotations: {}

strategy: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 33
  runAsUser: 33
  runAsNonRoot: true

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false

service:
  type: ClusterIP
  port: 80
  nodePort:
  clusterIP:
  loadBalancerIP:
  loadBalancerSourceRanges: []
  annotations: {}
  labels: {}

ingress:
  enabled: false
  className:
  maxBodySize: 64m
  annotations: {}
  labels: {}
  hosts:
    - host:
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  annotations: {}

customStartupProbe: {}
startupProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1
  periodSeconds: 10

customLivenessProbe: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
  periodSeconds: 10

customReadinessProbe: {}
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
  periodSeconds: 10

extraInitContainers: []
extraContainers: []

priorityClassName: ""

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: {}

revisionHistoryLimit:
podDisruptionBudget: {}

containerPort: 8000
env: []
args: []

externalDatabase: {}

settings:
  tablePrefix:
  maxFileUploadSize: 64M
  memoryLimit: 128M
  configExtra: |

customPhpConfig: |
apachePortsConfig: |
apacheDefaultSiteConfig: |

extraEnvSecrets:
  - name: wordpress-secrets   # <--- inject your Secret here

extraEnvConfigs: []
extraSecrets: []

storage:
  persistentVolumeClaimName:
  requestedSize:
  className:
  accessModes:
    - ReadWriteOnce
  keepPvc: false
  annotations: {}
  labels: {}

mariadb:
  enabled: false
  settings:
    rootPassword:
  userDatabase: {}
  storage:
    persistentVolumeClaimName:
    requestedSize:
    className:
    annotations: {}
    labels: {}

networkPolicy: {}

# Custom wp-config.php config map override
wpConfig:
  enabled: true
  source:
    configMap:
      name: wordpress-wp-config   # <--- your ConfigMap with wp-config.php
      key: wp-config.php
