replicaCount: 1

image:
  repository: wordpress
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

externalDatabase:
  host: mysql.mysql.svc.cluster.local   # the MySQL service DNS
  name: wordpress                        # database name
  user:
    secretName: wordpress-db-secret
    secretKey: username
  password:
    secretName: wordpress-db-secret
    secretKey: password

storage:
  accessModes:
    - ReadWriteOnce
  requestedSize: 1Gi
  className: standard

ingress:
  enabled: false
