# values.yaml for WordPress

wordpressUsername: admin
wordpressPassword: adminpassword123
wordpressEmail: tobbe.sjogren@hotmail.com
wordpressBlogName: testpage

service:
  type: NodePort
  port: 80

externalDatabase:
  host: my-mysql.default.svc.cluster.local
  user: wpuser
  password: wppassword123
  database: wordpress

persistence:
  enabled: true
  storageClass: "microk8s-hostpath"
  accessMode: ReadWriteOnce
  size: 10Gi

# No resource limits
resources: {}
